<?php
/**
 * LifetimeUsageObject
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lago\LagoPhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.31.0
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Lago\LagoPhpClient\Model;

use \ArrayAccess;
use \Lago\LagoPhpClient\ObjectSerializer;

/**
 * LifetimeUsageObject Class Doc Comment
 *
 * @category Class
 * @package  Lago\LagoPhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LifetimeUsageObject implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'LifetimeUsageObject';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'lago_id' => 'string',
        'lago_subscription_id' => 'string',
        'external_subscription_id' => 'string',
        'external_historical_usage_amount_cents' => 'int',
        'invoiced_usage_amount_cents' => 'int',
        'current_usage_amount_cents' => 'int',
        'from_datetime' => '\DateTime',
        'to_datetime' => '\DateTime',
        'usage_thresholds' => '\Lago\LagoPhpClient\Model\LifetimeUsageThresholdObject[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'lago_id' => 'uuid',
        'lago_subscription_id' => 'uuid',
        'external_subscription_id' => null,
        'external_historical_usage_amount_cents' => null,
        'invoiced_usage_amount_cents' => null,
        'current_usage_amount_cents' => null,
        'from_datetime' => 'date-time',
        'to_datetime' => 'date-time',
        'usage_thresholds' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'lago_id' => false,
        'lago_subscription_id' => false,
        'external_subscription_id' => false,
        'external_historical_usage_amount_cents' => false,
        'invoiced_usage_amount_cents' => false,
        'current_usage_amount_cents' => false,
        'from_datetime' => false,
        'to_datetime' => false,
        'usage_thresholds' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'lago_id' => 'lago_id',
        'lago_subscription_id' => 'lago_subscription_id',
        'external_subscription_id' => 'external_subscription_id',
        'external_historical_usage_amount_cents' => 'external_historical_usage_amount_cents',
        'invoiced_usage_amount_cents' => 'invoiced_usage_amount_cents',
        'current_usage_amount_cents' => 'current_usage_amount_cents',
        'from_datetime' => 'from_datetime',
        'to_datetime' => 'to_datetime',
        'usage_thresholds' => 'usage_thresholds'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'lago_id' => 'setLagoId',
        'lago_subscription_id' => 'setLagoSubscriptionId',
        'external_subscription_id' => 'setExternalSubscriptionId',
        'external_historical_usage_amount_cents' => 'setExternalHistoricalUsageAmountCents',
        'invoiced_usage_amount_cents' => 'setInvoicedUsageAmountCents',
        'current_usage_amount_cents' => 'setCurrentUsageAmountCents',
        'from_datetime' => 'setFromDatetime',
        'to_datetime' => 'setToDatetime',
        'usage_thresholds' => 'setUsageThresholds'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'lago_id' => 'getLagoId',
        'lago_subscription_id' => 'getLagoSubscriptionId',
        'external_subscription_id' => 'getExternalSubscriptionId',
        'external_historical_usage_amount_cents' => 'getExternalHistoricalUsageAmountCents',
        'invoiced_usage_amount_cents' => 'getInvoicedUsageAmountCents',
        'current_usage_amount_cents' => 'getCurrentUsageAmountCents',
        'from_datetime' => 'getFromDatetime',
        'to_datetime' => 'getToDatetime',
        'usage_thresholds' => 'getUsageThresholds'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('lago_id', $data ?? [], null);
        $this->setIfExists('lago_subscription_id', $data ?? [], null);
        $this->setIfExists('external_subscription_id', $data ?? [], null);
        $this->setIfExists('external_historical_usage_amount_cents', $data ?? [], null);
        $this->setIfExists('invoiced_usage_amount_cents', $data ?? [], null);
        $this->setIfExists('current_usage_amount_cents', $data ?? [], null);
        $this->setIfExists('from_datetime', $data ?? [], null);
        $this->setIfExists('to_datetime', $data ?? [], null);
        $this->setIfExists('usage_thresholds', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['lago_id'] === null) {
            $invalidProperties[] = "'lago_id' can't be null";
        }
        if ($this->container['lago_subscription_id'] === null) {
            $invalidProperties[] = "'lago_subscription_id' can't be null";
        }
        if ($this->container['external_subscription_id'] === null) {
            $invalidProperties[] = "'external_subscription_id' can't be null";
        }
        if ($this->container['external_historical_usage_amount_cents'] === null) {
            $invalidProperties[] = "'external_historical_usage_amount_cents' can't be null";
        }
        if ($this->container['invoiced_usage_amount_cents'] === null) {
            $invalidProperties[] = "'invoiced_usage_amount_cents' can't be null";
        }
        if ($this->container['current_usage_amount_cents'] === null) {
            $invalidProperties[] = "'current_usage_amount_cents' can't be null";
        }
        if ($this->container['from_datetime'] === null) {
            $invalidProperties[] = "'from_datetime' can't be null";
        }
        if ($this->container['to_datetime'] === null) {
            $invalidProperties[] = "'to_datetime' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets lago_id
     *
     * @return string
     */
    public function getLagoId()
    {
        return $this->container['lago_id'];
    }

    /**
     * Sets lago_id
     *
     * @param string $lago_id Unique identifier assigned to the lifetime usage record within the Lago application. This ID is exclusively created by Lago and serves as a unique identifier for the lifetime usage record within the Lago system
     *
     * @return self
     */
    public function setLagoId($lago_id)
    {
        if (is_null($lago_id)) {
            throw new \InvalidArgumentException('non-nullable lago_id cannot be null');
        }
        $this->container['lago_id'] = $lago_id;

        return $this;
    }

    /**
     * Gets lago_subscription_id
     *
     * @return string
     */
    public function getLagoSubscriptionId()
    {
        return $this->container['lago_subscription_id'];
    }

    /**
     * Sets lago_subscription_id
     *
     * @param string $lago_subscription_id Unique identifier assigned to the subscription record within the Lago application. This ID is exclusively created by Lago and serves as a unique identifier for the subscription record within the Lago system
     *
     * @return self
     */
    public function setLagoSubscriptionId($lago_subscription_id)
    {
        if (is_null($lago_subscription_id)) {
            throw new \InvalidArgumentException('non-nullable lago_subscription_id cannot be null');
        }
        $this->container['lago_subscription_id'] = $lago_subscription_id;

        return $this;
    }

    /**
     * Gets external_subscription_id
     *
     * @return string
     */
    public function getExternalSubscriptionId()
    {
        return $this->container['external_subscription_id'];
    }

    /**
     * Sets external_subscription_id
     *
     * @param string $external_subscription_id The subscription external unique identifier (provided by your own application).
     *
     * @return self
     */
    public function setExternalSubscriptionId($external_subscription_id)
    {
        if (is_null($external_subscription_id)) {
            throw new \InvalidArgumentException('non-nullable external_subscription_id cannot be null');
        }
        $this->container['external_subscription_id'] = $external_subscription_id;

        return $this;
    }

    /**
     * Gets external_historical_usage_amount_cents
     *
     * @return int
     */
    public function getExternalHistoricalUsageAmountCents()
    {
        return $this->container['external_historical_usage_amount_cents'];
    }

    /**
     * Sets external_historical_usage_amount_cents
     *
     * @param int $external_historical_usage_amount_cents The historical usage amount in cents for the subscription (provided by your own application).
     *
     * @return self
     */
    public function setExternalHistoricalUsageAmountCents($external_historical_usage_amount_cents)
    {
        if (is_null($external_historical_usage_amount_cents)) {
            throw new \InvalidArgumentException('non-nullable external_historical_usage_amount_cents cannot be null');
        }
        $this->container['external_historical_usage_amount_cents'] = $external_historical_usage_amount_cents;

        return $this;
    }

    /**
     * Gets invoiced_usage_amount_cents
     *
     * @return int
     */
    public function getInvoicedUsageAmountCents()
    {
        return $this->container['invoiced_usage_amount_cents'];
    }

    /**
     * Sets invoiced_usage_amount_cents
     *
     * @param int $invoiced_usage_amount_cents The total invoiced usage amount in cents for the subscription.
     *
     * @return self
     */
    public function setInvoicedUsageAmountCents($invoiced_usage_amount_cents)
    {
        if (is_null($invoiced_usage_amount_cents)) {
            throw new \InvalidArgumentException('non-nullable invoiced_usage_amount_cents cannot be null');
        }
        $this->container['invoiced_usage_amount_cents'] = $invoiced_usage_amount_cents;

        return $this;
    }

    /**
     * Gets current_usage_amount_cents
     *
     * @return int
     */
    public function getCurrentUsageAmountCents()
    {
        return $this->container['current_usage_amount_cents'];
    }

    /**
     * Sets current_usage_amount_cents
     *
     * @param int $current_usage_amount_cents The current usage amount in cents for the subscription on the current billing period.
     *
     * @return self
     */
    public function setCurrentUsageAmountCents($current_usage_amount_cents)
    {
        if (is_null($current_usage_amount_cents)) {
            throw new \InvalidArgumentException('non-nullable current_usage_amount_cents cannot be null');
        }
        $this->container['current_usage_amount_cents'] = $current_usage_amount_cents;

        return $this;
    }

    /**
     * Gets from_datetime
     *
     * @return \DateTime
     */
    public function getFromDatetime()
    {
        return $this->container['from_datetime'];
    }

    /**
     * Sets from_datetime
     *
     * @param \DateTime $from_datetime The recording start date and time of the subscription lifetime usage. The date and time must be in ISO 8601 format.
     *
     * @return self
     */
    public function setFromDatetime($from_datetime)
    {
        if (is_null($from_datetime)) {
            throw new \InvalidArgumentException('non-nullable from_datetime cannot be null');
        }
        $this->container['from_datetime'] = $from_datetime;

        return $this;
    }

    /**
     * Gets to_datetime
     *
     * @return \DateTime
     */
    public function getToDatetime()
    {
        return $this->container['to_datetime'];
    }

    /**
     * Sets to_datetime
     *
     * @param \DateTime $to_datetime The recording end date and time of the subscription lifetime usage. The date and time must be in ISO 8601 format.
     *
     * @return self
     */
    public function setToDatetime($to_datetime)
    {
        if (is_null($to_datetime)) {
            throw new \InvalidArgumentException('non-nullable to_datetime cannot be null');
        }
        $this->container['to_datetime'] = $to_datetime;

        return $this;
    }

    /**
     * Gets usage_thresholds
     *
     * @return \Lago\LagoPhpClient\Model\LifetimeUsageThresholdObject[]|null
     */
    public function getUsageThresholds()
    {
        return $this->container['usage_thresholds'];
    }

    /**
     * Sets usage_thresholds
     *
     * @param \Lago\LagoPhpClient\Model\LifetimeUsageThresholdObject[]|null $usage_thresholds Array of usage thresholds attached to the subscription's plan.
     *
     * @return self
     */
    public function setUsageThresholds($usage_thresholds)
    {
        if (is_null($usage_thresholds)) {
            throw new \InvalidArgumentException('non-nullable usage_thresholds cannot be null');
        }
        $this->container['usage_thresholds'] = $usage_thresholds;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


