<?php
/**
 * CustomerCreateInputCustomerIntegrationCustomersInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lago\LagoPhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.31.0
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Lago\LagoPhpClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CustomerCreateInputCustomerIntegrationCustomersInnerTest Class Doc Comment
 *
 * @category    Class
 * @description CustomerCreateInputCustomerIntegrationCustomersInner
 * @package     Lago\LagoPhpClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CustomerCreateInputCustomerIntegrationCustomersInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CustomerCreateInputCustomerIntegrationCustomersInner"
     */
    public function testCustomerCreateInputCustomerIntegrationCustomersInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "integration_type"
     */
    public function testPropertyIntegrationType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "integration_code"
     */
    public function testPropertyIntegrationCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "external_customer_id"
     */
    public function testPropertyExternalCustomerId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sync_with_provider"
     */
    public function testPropertySyncWithProvider()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subsidiary_id"
     */
    public function testPropertySubsidiaryId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
