<?php
/**
 * WalletCreateInputWalletTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Lago\LagoPhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.31.0
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Lago\LagoPhpClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * WalletCreateInputWalletTest Class Doc Comment
 *
 * @category    Class
 * @description WalletCreateInputWallet
 * @package     Lago\LagoPhpClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class WalletCreateInputWalletTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WalletCreateInputWallet"
     */
    public function testWalletCreateInputWallet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rate_amount"
     */
    public function testPropertyRateAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paid_credits"
     */
    public function testPropertyPaidCredits()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "granted_credits"
     */
    public function testPropertyGrantedCredits()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "external_customer_id"
     */
    public function testPropertyExternalCustomerId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "expiration_at"
     */
    public function testPropertyExpirationAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "invoice_requires_successful_payment"
     */
    public function testPropertyInvoiceRequiresSuccessfulPayment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "transaction_metadata"
     */
    public function testPropertyTransactionMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "applies_to"
     */
    public function testPropertyAppliesTo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "recurring_transaction_rules"
     */
    public function testPropertyRecurringTransactionRules()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
